### ISSUE TITLE
Support bypassing Authentication in CI/testing environment

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#762] opened 2023-01-30 16:02 UTC
In order to get Cypress tests working, we need a way to for a headless browser to access pages that are currently behind authentication.

The FAC Frontend app managed this by [setting an `in_CI` environment variable](https://github.com/GSA-TTS/FAC-Frontend/search?q=in_ci). Some other possible approaches are described in [this slack thread](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1675088011485539).

In order to unblock #729, we need to ensure that:

- [x] Cypress tests are able to run in CI; and
- [x] The solution can also be applied in local dev environments

**Comment by timoballard** [comment] 2023-02-03 21:59
With the changes in #769, you can (effectively) bypass authentication by setting an environment variable `DISABLE_AUTH` to `true`. Doing so activates middleware that authenticates all incoming requests as `test_user@test.test`. I didn't close this ticket because the AC includes verifying that Cypress does work as intended after this change, which I didn't do as part of #769

**Closed** 2023-03-16 21:08 UTC
Labels: engineering
