### ISSUE TITLE
Sam.gov connection errors

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#376] opened 2022-07-19 17:11 UTC

**Comment by tadhg-ohiggins** [comment] 2022-07-19 17:15
*   We don't know what the cause of the errors (403s?) is yet.
*   It's possible our existing key has expired.
*   We may have access to another key already, and should try that.
*   If not, we may have to apply for another key; until we have an ATO SAM.gov will only provide keys tied to individuals (not to applicatios) which may have shorter lifespans.
*   We likely need another issue for “track SAM.gov key lifetime and build process for renewing key”.

**Comment by heymatthenry** [comment] 2022-07-19 17:19
This is what I'm seeing on the front end: 

`"valid":false,"errors":{"auditee_uei":["SAM.gov API response status code invalid: 403"]}}`

**Comment by petermarks-gsa** [comment] 2022-07-20 15:13
@tadhg-ohiggins Who should we assign this blocking issue to?

**Comment by tadhg-ohiggins** [comment] 2022-07-20 19:48
Switching the API key via the cloud.gov dashboard (but not via the GitHub secrets plus deploy.yml process) worked. Closing.

**Closed** 2022-07-20 19:48 UTC
Labels: bug, engineering
