### ISSUE TITLE
[HD]: Workbook validation error not giving explanation.

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2534] opened 2023-10-18 13:15 UTC
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/487

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

We are receiving a failure to validate message when attempting to upload workbook 3 federal award findings. 

There are two different sets of instructions we are told to follow:

Workbook 3 instructions say to leave the prior year finding blank if the prior year finding is not appliable
The error message we receive when we do this says to enter N/A if the prior year finding is not applicable
When we enter N/A it rejects the file
Please advise.
![image001](https://github.com/GSA-TTS/FAC/assets/139488747/6d30c6fb-3ac4-409e-b08f-489b8ac28cc4)

**Comment by danswick** [comment] 2023-10-25 23:48
duplicate of https://github.com/GSA-TTS/FAC/issues/2545. Let's track there!

**Closed by danswick** 2023-10-25 23:48 UTC
Labels: helpdesk
