### ISSUE TITLE
FAC - Bug: POST /audit/auditee-certification-confirm creating 500 error with invalid date input

### ISSUE THREAD

**Issue by rnovak338** [GSA-TTS/FAC#4186] opened 2024-08-14 20:13 UTC
### Describe the bug

A 500 error response to the endpoint caught from the past week:
`POST /audit/auditee-certification-confirm/2022-06-GSAFAC-0000052214`

NewRelic log can be found [here](https://one.newrelic.com/logger?account=3919076&duration=604800000&state=3c3c869e-5ac9-c2b3-e72b-f7787a1701f9).

When `auditee-certification-date-signed` in the payload of this request is provided an incorrect format (e.g. "204-08-12") the backend returns a 500 error response.

### Steps to reproduce the bug

On the Auditor or Auditee certification steps when the signature must be filled out, you will be able to supply a date for your signature. By typing `MM/DD/0204`, this error will occur.

**Note** - Do not skip out on the leading zero (e.g. `MM/DD/204`) as the front-end input validation will trigger.

### Expected Behavior

The user is likely expected to get a data-validation prompt when an invalid date is inputted rather than a 500 response.

### Screenshots

<img width="347" alt="image" src="https://github.com/user-attachments/assets/ebf88bc2-bd12-46e6-9ea3-2690a169bb96">

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by rnovak338** [comment] 2024-08-14 20:14
@danswick not sure how to flesh out the "Steps to Reproduce" as these have been found through NewRelic. Please advise.

**Comment by danswick** [comment] 2024-08-14 20:43
We can reproduce by creating a fake submission on staging, marking as "Ready for certification," then manually navigating to the auditee certification page and confirming the 500.

What do you think possible solution looks like? We could check the report's status when a user navigates to that page, providing a message that prevents them from trying to certify. Or we could let them submit and provide a useful error message. Or maybe something else?

**Comment by rnovak338** [comment] 2024-08-15 14:56
@danswick Strangely enough, this appears to be the first case this year from querying NewRelic for the error.

**Closed** 2024-10-01 20:13 UTC
Labels: bug
