### ISSUE TITLE
Excel attachment ingestion

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#772] opened 2023-02-06 21:53 UTC
### Background

Users need to be able to upload and download Excel files associated with their submissions. (See [ADR](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0015-store-uploaded-excel-files.md#validation).)

- Excel download view
  - Associated access permissions.
  - Linking to the files from the view for the submission.
- frontend upload functionality / validation
- frontend download functionality

### Acceptance Criteria (We'll know we're done when...)

- [ ]   Users can upload Excel files associated with their submissions, and other users can download them.
- [ ]   Excel files that pass the first [five validation levels](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0015-store-uploaded-excel-files.md#validation) will have their contents extracted and stored in the database.
- [ ]   Invalid Excel files will be rejected with appropriate error messaging

```[tasklist]
### Stories
- [x] #777 
- [ ] #778
- [ ] #779 
- [ ] #780 
- [ ] #781
- [ ] #782 
- [ ] #783 
- [ ] #784 
- [ ] https://github.com/GSA-TTS/FAC/issues/727
```

See issues associated with outline above.

**Comment by mogul** [comment] 2023-02-23 22:28
I migrated everything over to https://github.com/GSA-TTS/FAC/issues/449 and I'm closing this one as a dupe of that epic.

**Closed by mogul** 2023-02-23 22:28 UTC
Labels: engineering, story
