### ISSUE TITLE
[intake] Figure out why a particular workbook only validates if resaved

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2515] opened 2023-10-16 20:56 UTC
Follow up to https://github.com/GSA-TTS/FAC/issues/2409 

### Tasks

```[tasklist]
- [ ] Add some print statements/breakpoints to the IR code
- [ ] Running locally, upload workbook from #2409 and examine the IR output
```

**Comment by jadudm** [comment] 2024-01-20 13:32
We resolved the root cause on this elsewhere, and I'm not sure if this ticket tracks anything we still want to do. Closing for now.

**Closed by jadudm** 2024-01-20 13:32 UTC
