### ISSUE TITLE
🅢 design "SF-SAC: General Info" page - As a user, I want to know how SAM.gov will autopopulate some data

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#304] opened 2022-07-01 16:23 UTC
Breakout issue of #274 

**Background**
[Sprint 6 research -  observations/refinements by page](https://docs.google.com/document/d/1Y8g7HEd6eysBQjg3x_-K3nzk9M9xBCp5w8eZXql_8xQ/edit#heading=h.ycduc4d91ltn)

**Observation(s)**
- Some users spoke of wanting to see more of the fields here pre-populated based on earlier entries or existing data from SAM.gov (UEI, Auditee Information such as name, address).
- At least one user didn’t seem to require the subsection navigation in the sidebar (this was when the prototype had fixed scrolling on that element). No other users noticed.

**MVP recommendation(s)**
- Perhaps we can nix the subsection navigation in the sidebar altogether? Doing so could clean that up and make that easier to enable as a fixed scroll element (not sure if we necessarily need to do the latter).
- It may not need to be reflected on a screen per se, but maybe there needs to be some annotations or notes somewhere that indicate clearly what fields can/should be auto populated based on existing data to limit duplicate efforts.
  - [Something similar in the implementation notes on Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2464%3A10748) — is this what you mean @sreuber ?

**Tasks**
- [x] Review sprint 6 research analysis
- [x] Create checklists for refinement needed to each page
- [x] Update #274 with the checklist of refinements needed
- [ ] Make refinements
- [ ] Peer review

**Definition of done**
**Acceptance Criteria (We'll know we're done when...)**
- [ ] Screens in Figma are ready to be handed off to front end
- [x]  All text has a contrast ratio of 4.5:1 with the background
- [ ]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment] 2022-07-05 20:09
The scope of this is really just adding some copy to let folks know anout the auditee address field. 

Auditee address should be autopopulated from SAM.gov. This field should not be editable here. If people don’t have a valid UEI, these fields will be uneditable and blank. We’ll want to include some copy that tells them these fields will be populated by sam.gov when they add a UEI.

**Comment by melchoyce** [comment] 2022-07-19 22:19
To clarify...

1. If they enter a valid UEI, the "Auditee information" section will be pre-populated with information from SAM.gov, which we should communicate to users.
2. If they don't enter a valid/any UEI, the information will be blank. We should inform them this information will pre-populate once they enter a valid UEI.

Is this correct? Is there any other information that gets pre-populated?

**Comment by austinhernandez** [comment] 2022-07-20 20:19
I cant think of anything else, a Report ID # gets generated regardless, but not pre-populated, you have to manually enter the entity type...

**Comment by melchoyce** [comment] 2022-07-20 21:40
@tadhg-ohiggins In case there's any other SAM.gov auto-populated content we missed ^

**Comment by tadhg-ohiggins** [comment] 2022-07-20 22:14
As far as I know, we get UEI, auditee name, and auditee mailing address. (If we get anything; there may be cases where we get no results, and there may be cases where we get UEI and zero, one, or two of the other fields.)

**Comment by melchoyce** [comment] 2022-07-21 13:42
Awesome, thanks for confirming!

**Comment by melchoyce** [comment] 2022-08-02 16:34
**If you have a UEI already entered and confirmed:**

![Screen Shot 2022-08-02 at 12 21 52 PM](https://user-images.githubusercontent.com/2846578/182424421-1e95e2f2-1011-4054-886f-cf675ed9303e.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4038%3A20103)

**If you don't have a UEI confirmed**

![image](https://user-images.githubusercontent.com/2846578/182426703-2fb8da64-6260-43ed-819c-d0e0bccf62ee.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4189%3A19746) | [Prototype](https://www.figma.com/proto/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?page-id=3954%3A19341&node-id=4189%3A19746&viewport=-500%2C509%2C0.16&scaling=min-zoom&starting-point-node-id=4189%3A19746)

Overall feeling pretty uncertain about this, definitely need some peer feedback @austinhernandez @sreuber

**Comment by austinhernandez** [comment] 2022-08-04 18:48
I didnt work on this section, so I am less familiar with it than the other pages, but this seems right

- I remember users wanting to put in an auditee name even with an invalid UEI so they could find it easily. 
  - I also recall a few users say they wouldnt even proceed without an invalid UEI bc they were unsure if it was a server error or what would happen next.  
- Q: With an invalid UEI, they can enter in all this information. Does it just gets overwritten when the correct info is put in? Does that need some kind of notification? 
- Is this the only place you can update to a valid UEI?
- I just wanted to note about disabled and read-only form fields for screen readers as it has been confusing for me in the past: https://tink.uk/screen-reader-support-for-disabled-read-only-form-fields/

**Comment by melchoyce** [comment] 2022-08-04 22:50
> Is this the only place you can update to a valid UEI?

This is the second opportunity auditor/ees have to fill out UEI, the first of which being in the "Create Audit" flow:

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=2552%3A11276

If they confirmed their UEI in that flow, then when they get to this screen, we've already pre-populated their information. We don't want their information to get out of sync with what's coming from SAM.gov, so they can't change any pre-populated information (without changing the UEI). 

If they haven't confirmed their UEI, this is their second chance to correct that.

> Is this the only place you can update to a valid UEI?

We currently have an "edit" link next to the UEI in the header of each of these pages: 

![Screen Shot 2022-08-04 at 6 36 28 PM](https://user-images.githubusercontent.com/2846578/182964309-8ba992fa-7087-4a98-b7fa-80a30b00534d.png)

Which then opens up this modal, which I've based this page's flow on:

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3136%3A18722

![image](https://user-images.githubusercontent.com/2846578/182964627-bc281c6e-2b0a-455c-8f5f-597376844462.png)

> Q: With an invalid UEI, they can enter in all this information. Does it just gets overwritten when the correct info is put in? Does that need some kind of notification?

Yeah you know what that's a great point, I should just remove those fields if you have't confirmed your UEI, since they _would_ get overwritten once you enter a valid number.

> I just wanted to note about disabled and read-only form fields for screen readers as it has been confusing for me in the past: https://tink.uk/screen-reader-support-for-disabled-read-only-form-fields/

Thank you!! I'll review this.

**Comment by austinhernandez** [comment] 2022-08-05 17:15
I'm wondering if it makes sense to have the `edit UEI` link go to the "SF-SAC: General Info" page since more than just the UEI is updating and it will remove the information that was added before.

Also, will the UEI be editable always or only in the case of an invalid UEI?

**Comment by tadhg-ohiggins** [comment] 2022-08-05 17:23
Here are my thoughts on editing UEI and its related fields:

### Flow with successful UEI lookup

UEI and auditee name (and likely auditee address, in future) will be populated and non-editable. To change the UEI, the user will have to go through a flow that should basically replicate the flow of their initially entering it. This includes the path for an unsuccessful UEI lookup.

### Flow with unsuccessful UEI lookup

The user has to enter auditee name (and likely address, in future). These (including UEI) will be shown as non-editable in the general view, just as with the successful UEI flow. To change them, the user will have to go through a flow that should basically replicate the flow of their initially trying to enter UEI.

In the short term, however, this special flow for editing later doesn't exist, so whatever happens first time through is going to stay that way until the edit flow is implemented.

**Comment by tadhg-ohiggins** [comment] 2022-08-05 17:27
Those thoughts are based on the technical constraints around the fact that these fields are special, in they they're not supposed to be user-editable but we're supporting some cases where they are because we can't fully rely on UEI.

**Comment by melchoyce** [comment] 2022-08-05 22:27
Thanks @tadhg-ohiggins! 

Based on this feedback and a conversation with @austinhernandez, I've explored what it could look like if you confirmed your UEI during the Audit Start section:

![image](https://user-images.githubusercontent.com/2846578/183218525-4886afeb-0516-4802-926d-8ede51f427e0.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4354%3A22378)

If previously confirmed, the UEI is no longer editable. (Austin and I agreed that once you confirm your UEI, it shouldn't be editable **anywhere**. Please let us know if this should not be the case!) 

I've grouped the UEI, along with any information populated by SAM.gov, into the same section as informational text. I opted to not use `readonly` text fields due to the accessibility concerns in the article Austin linked above.

If this seems like the right track, I'll work on updating the flow for if you have **not** previously confirmed your UEI.

I also added a little more information to the "more numbers to add" questions to make it more clear that if you do have more numbers to add, you'll be able to do so later in the field.

For the future, it might also be worth looking at merging the "add multiple EINs/UEIs" pages into this one, depending on if:
1. We're accepting Excel uploads; or
2. It's never more than a handful of additional numbers.

**Comment by petermarks-gsa** [comment] 2022-08-08 17:27
@melchoyce From my perspective, implementation for this will be covered in https://github.com/GSA-TTS/FAC/issues/402. We can discuss specifics at backlog refinement tomorrow. Proposing we close this for now.

**Closed by petermarks-gsa** 2022-08-08 17:27 UTC
Labels: design, effort-S

**Comment by melchoyce** [comment] 2022-08-08 21:53
One last update — cleaned up the page and designed how to access the UEI search modal when your UEI isn't confirmed: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4398%3A21480

**Comment by tadhg-ohiggins** [comment] 2022-08-09 17:44
We decided that the field for *Auditee email* should be a text field, not a dropdown.
