### ISSUE TITLE
Revise: search results, audit summary page

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3307] opened 2024-01-27 19:42 UTC
## Background

Now that GSA is the *only* source for data, how we present it matters more. Things about our presentation that were potentially inconvenient now will block people from doing their work.

Recommended changes...

### Search results

1. Search results should use our accepted/standard language for "accepted date," whatever that is. (See Slack convo.)
2. Cog/over needs to link to a page on our static site that explains what it is, and provides a list of agency numbers and NSAC email addresses. Or, the PDF with this information should be on that page. Either way, this is useless/unusable as-is. 
3. UEI or EIN needs to actually be either.
    1. If the UEI exists, and is not `GSA_MIGRATION`, show that.
    2. If the UEI is `GSA_MIGRATION`, show the EIN.
    3. If both are `GSA_MIGRATION`, show `GSA_MIGRATION`
4. Add the time the search took to the top of the search results. "Results: 10314, 7.2 seconds"
5. Add 18, 17, 16 back to the year selection. The data is coming.

### Summary page

 1. Remove links to workbooks at bottom of page. Keep summary data (e.g. "Findings: 3", but no link).
 2. Add EIN to top summary under UEI if it exists. Do not show the UEI if it is `GSA_MIGRATION`.
 3. Apply pretty formatting to phone numbers. Eg. 2075551212 becomes (207)-555-1212
 4. In a row, under the summary/buttons, but before everything else:

| | | |
| --- | --- | --- |
| Awards: 3 | Findings: 1 | Expenditure: $36,032,303 |

Or, find a way to topline the number of awards, findings, and expenditures.

### Timing estimate

We should put it in `preview` and ask 2-3 users what they think after these changes. Or, put another way, timebox to one week some followup on these changes, and then get them in. Total time on this should be no more than 2w front-to-back. Or, ~1w for the changes, and 1w for a checkin with users. If the users we email with a link to consider don't reply, publish regardless.

**Comment by danswick** [comment] 2024-04-01 17:20
I think this was intended to be a tracking issue for two different scopes of work: search page and summary page. I copied the relevant text from here into those issues and am closing here.

**Closed by danswick** 2024-04-01 17:20 UTC
