### ISSUE TITLE
FAC - Bug: POST /audit/auditee-certification-confirm creating 500 error with FSM

### ISSUE THREAD

**Issue by rnovak338** [GSA-TTS/FAC#4185] opened 2024-08-14 20:13 UTC
### Describe the bug

A 500 error response caught regarding the Django FSM for the audits from the following endpoints:

`POST /audit/auditee-certification-confirm/2023-12-GSAFAC-0000050065`
`POST /audit/auditee-certification-confirm/2021-12-GSAFAC-0000050302`

### Steps to reproduce the bug

You can reproduce this error by creating a fake submission on staging, marking it as "Ready for certification," and then manually navigating to the auditee certification page to confirm the 500 error.

### Expected Behavior

These audits should not be attempting to transition to `auditee_certified` unless they are in the `auditor_certified` states.

In case 1 (`2023-12-GSAFAC-0000050065`), the audit is in the `ready_for_certification` state. ([NewRelic](https://one.newrelic.com/logger?account=3919076&duration=604800000&state=9a4ca8a2-eec1-c72d-22eb-42ba2cf5de21))
In case 2 (`2021-12-GSAFAC-0000050302`), the audit is already in the `auditee_certified` state. ([NewRelic](https://one.newrelic.com/logger?account=3919076&duration=604800000&state=bc51f15d-80d2-692c-d1f8-8b303e8ead3e))

### Screenshots

`POST /audit/auditee-certification-confirm/2023-12-GSAFAC-0000050065`
<img width="344" alt="image" src="https://github.com/user-attachments/assets/c9c69c40-9c8c-485e-bd51-9774221adeec">

`POST /audit/auditee-certification-confirm/2021-12-GSAFAC-0000050302`
<img width="343" alt="image" src="https://github.com/user-attachments/assets/6fbc2e9c-38c3-4618-9169-afd020de9e4e">

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by rnovak338** [comment] 2024-08-14 20:14
@danswick not sure how to flesh out the "Steps to Reproduce" as these have been found through NewRelic. Please advise.

**Comment by danswick** [comment] 2024-08-14 20:44
We can reproduce by creating a fake submission on staging, marking as "Ready for certification," then manually navigating to the auditee certification page and confirming the 500.

What do you think possible solution looks like? We could check the report's status when a user navigates to that page, providing a message that prevents them from trying to certify. Or we could let them submit and provide a useful error message. Or maybe something else?

**Comment by rnovak338** [comment] 2024-08-15 14:43
@danswick sounds good, I'll update the ticket.

If the UI does not normally permit a user from visiting a certain page based on the current report status, then I would suggest your first option - we throw an error if a user bypasses our UI to visit it.

**Closed** 2024-10-01 20:13 UTC
Labels: bug
