### ISSUE TITLE
[HD]: Cluster Error: G2 cluster name needs to be selected

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2421] opened 2023-10-05 20:00 UTC
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/208

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/u/2/folders/1mG-xq6qtl6TSDyvSSRwInvz_CYY4h1oo

### What happened?

I keep getting an error that G2 cluster name needs to be selected from the approved cluster names.  I believe it is completed correctly, but I keep getting the same error.  What do I need to do differently?

**Comment by danswick** [comment] 2023-10-06 20:51
I tested this out and it looks like the cause is the "N/A" values in columns `H` and `I`. We should handle these kinds of validation issues more gracefully on our end in the future (hopefully soon when we focus on improved validation/error messaging).

**Comment by jadudm** [comment] 2023-10-07 17:06
This is fixed via #2440.

**Closed** 2023-10-18 22:33 UTC
Labels: cx, helpdesk
