### ISSUE TITLE
[HD]: Reference numbers must be formatted YYYY-NNN

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2530] opened 2023-10-17 21:19 UTC
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/446

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

From user: 

Hello James,

I have read the instructions for completing the federal-awards-workbook and the federal-awards-findings-workbook and have carefully completed the forms, ensuring that the format of the finding is correct and there are no blanks in the audit findings column.  However, when I upload the federal-awards-findings-workbook, I get the same error message; "Reference numbers must be formatted YYYY-NNN".

Please help...

**Comment by danswick** [comment] 2023-10-25 23:53
I believe this is a duplicate of https://github.com/GSA-TTS/FAC/issues/2545. It should be resolved by the work tracked in https://github.com/GSA-TTS/FAC/issues/2553.

**Closed by danswick** 2023-10-25 23:53 UTC
Labels: helpdesk
