### ISSUE TITLE
Add privacy policy link

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3876] opened 2024-05-22 18:47 UTC
As part of our ATO process, we found that [NIST AC-8](https://csf.tools/reference/nist-sp-800-53/r5/ac/ac-8/) is not being met.

This would have (until a few days ago) required a pop-up with a large, scary banner. 

Now, we need to add a privacy policy link to the footer of our static site and app ([GSA guidance](https://docs.google.com/document/d/1VYyelBHwdA5tq60a0Zn3Vc8jt_MaASY47OnngW1J988/edit)).

```[tasklist]
### We'll know we're done when
- [ ] We've added the link to GSA privacy policy in the footer of the static site
- [ ] We've added the link to GSA privacy policy in the footer of the app
```

**Comment by danswick** [comment] 2024-05-28 16:57
Noting the login.gov "Rules of use" UI ([link](https://www.login.gov/policy/rules-of-use/)): 

<img width="659" alt="image" src="https://github.com/GSA-TTS/FAC/assets/2365503/315cf28a-36f8-4f57-baf3-44ce2afd7dee">

**Comment by phildominguez-gsa** [comment] 2024-08-06 16:19
@danswick This looks like a duplicate of https://github.com/GSA-TTS/FAC/issues/3877

**Closed** 2024-10-18 15:58 UTC
Labels: content
